### PR TITLE
Add file deletion options for rotated files

### LINKED ISSUE #70: Allow to limit the number of files created by AdvancedFileOutput
Log rotation is not only about splitting logs between multiple files but also about limiting the number of those files.
What do you think about a setting in the AdvancedFileOutput class to limit the count of archived files?

Suggested logic:
- the active file `_file` should not be considered for the count
- at every rotation:
  - count files different to `_file` in the destination folder
  - sort files by creation date asc
  - remove the first file in the list until the list length is not equal to maximum number of files accepted
- the default value for `maximumArchivedLogFiles` should be null, so that it keeps the current behaviour without cancellations

I will be happy to provide a PR, let me know if it could be reasonable

### PR DESCRIPTION
**Pull request by lomby92**
Closes #70

### CODE REVIEW

**Comment by lomby92** [comment]
If you need any explanation on the implementation, feel free to reach me out

**Review by Bungeefan — APPROVED** [review]

**Comment by Bungeefan** [comment]
Your tests seem to be kind of flaky, especially on GitHub Actions :thinking:

**Comment by Bungeefan** [comment]
That's quite interesting.
After some tests on my part, I found that the only test that is flaky on my machine is the "custom file sorter" (fixable with a small timeout, probably because of file system flush) but for GitHub Actions it seems like it's only struggling with the regular "files deletion" one.
I can't really reproduce this on my side yet...

**Comment by lomby92** [comment]
Really interesting since i didn't encountered problems during development.

**OS**: Fedora Linux
**Kernel**: 6.8.7-100
**Flutter**: 3.19.5
**Dart**: 3.3.3

**Comment by Bungeefan** [comment]
After some tests with my private Jenkins (where I could reproduce the GitHub Actions failures), I found out that `1000ms` seem to be minimal sleep duration that doesn't trigger any flakiness in the test.

I still want to find out why there is such a flakiness even with some sleep steps in the test, however, as this doesn't seem to be a problem in your code and shouldn't impact any users, I will no longer delay the release of `2.3.0`.

logger [v2.3.0](https://pub.dev/packages/logger/versions/2.3.0) has been successfully published on pub.dev!

**Pull request merged**
